
---
- name: Pi-hole (with Traefik) Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ pihole_data_directory }}/etc/pihole"
    - "{{ pihole_data_directory }}/var/log/lighttpd"

- name: Pi-hole (with Traefik) Docker Container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    pull: false
    volumes:
      - "{{ pihole_data_directory }}/etc/pihole:/etc/pihole:rw"
      - "{{ pihole_data_directory }}/etc/dnsmasq.d:/etc/dnsmasq.d:rw"
      - "{{ pihole_data_directory }}/var/log:/var/log:rw"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8182:80"
      - "8183:443"
    env:
      DNS1: "{{ pihole_dns1 }}"
      DNS2: "{{ pihole_dns2 }}"
      ServerIP: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      WEBPASSWORD: "{{ pihole_WEBPASSWORD }}"
      PROXY_LOCATION: "pihole"
      TZ: "{{ ansible_nas_timezone }}"
      VIRTUAL_HOST: "pihole.{{ ansible_nas_domain }}"
      VIRTUAL_PORT: "80"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.backend: "pihole"
      traefik.port: "80"
      traefik.frontend.rule: "HostRegexp:pihole.{{ ansible_nas_domain }},{catchall:.*}"
      traefik.frontend.priority: "1"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.STSSeconds: "315360000"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.SSLHost: "{{ ansible_nas_domain }}"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.frameDeny: "true"
    memory: 1g
