##                       ._____.   .__
##  _____    ____   _____|__\_ |__ |  |   ____             ____ _____    ______
##  \__  \  /    \ /  ___/  || __ \|  | _/ __ \   ______  /    \\__  \  /  ___/
##   / __ \|   |  \\___ \|  || \_\ \  |_\  ___/  /_____/ |   |  \/ __ \_\___ \
##  (____  /___|  /____  >__||___  /____/\___  >         |___|  (____  /____  >
##       \/     \/     \/        \/          \/               \/     \/     \/
##     a n s i b l e - n a s      https://github.com/davestephens/ansible-nas

# Add your all.yml config overrides to this file. See group_vars/all.yml for all possible settings.

# Example options
ansible_nas_hostname: ansible-nas
ansible_nas_timezone: Etc/UTC

## Enable some applications
heimdall_enabled: true
portainer_enabled: true
transmission_enabled: true
# emby_enabled: true
# plex: true
# serposcope_enabled: true
# pyload_enabled: true
radarr_enabled: true
homeassistant_enabled: true
glances_enabled: true
jellyfin_enabled: true
jackett_enabled: true
# sonarr_enabled: false
# grafana_enabled: false
# telegraf_enabled: true
# grafana_available_externally: true
youtubedlmaterial_enabled: true
nextcloud_enabled: true
# airsonic_enabled: false
pihole_without_traefik_enabled: false
